# Generated by Django 4.2.9 on 2026-03-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kontrak', models.CharField(max_length=50, unique=True, verbose_name='Nomor Kontrak')),
                ('tipe_kontrak', models.CharField(choices=[('Perjanjian Harian Lepas', 'Perjanjian Harian Lepas'), ('Borongan', 'Borongan'), ('PKWT', 'Perjanjian Kerja Waktu Tertentu (PKWT)'), ('PKWTT', 'Perjanjian Kerja Waktu Tidak Tertentu (PKWTT)')], max_length=50, verbose_name='Tipe Kontrak')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('jabatan', models.CharField(blank=True, max_length=100)),
                ('departemen', models.CharField(blank=True, max_length=100)),
                ('gaji_pokok', models.BigIntegerField(default=0, verbose_name='Gaji Pokok')),
                ('status_gaji', models.CharField(choices=[('reguler', 'Reguler'), ('all_in', 'All-In')], default='reguler', max_length=10, verbose_name='Status Gaji')),
                ('nama_penandatangan', models.CharField(blank=True, max_length=100, verbose_name='Nama Penandatangan')),
                ('jabatan_penandatangan', models.CharField(blank=True, max_length=100, verbose_name='Jabatan Penandatangan')),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Expired', 'Expired'), ('Terminated', 'Terminated'), ('Renewed', 'Diperpanjang')], default='Aktif', max_length=20)),
                ('file_kontrak', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kontrak',
                'verbose_name_plural': 'Kontrak',
                'ordering': ['-tanggal_mulai'],
            },
        ),
    ]
