# Generated by Django 4.2.9 on 2026-03-12 12:37

import apps.psychotest.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoalBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('logika', 'Logika'), ('verbal', 'Verbal'), ('numerik', 'Numerik'), ('disc', 'DISC Personality')], max_length=20)),
                ('tipe', models.CharField(choices=[('pilihan_ganda', 'Pilihan Ganda'), ('disc_set', 'DISC Set (pilih paling/kurang)')], default='pilihan_ganda', max_length=20)),
                ('pertanyaan', models.TextField(verbose_name='Pertanyaan / Soal')),
                ('opsi_a', models.CharField(blank=True, max_length=300, verbose_name='Opsi A')),
                ('opsi_b', models.CharField(blank=True, max_length=300, verbose_name='Opsi B')),
                ('opsi_c', models.CharField(blank=True, max_length=300, verbose_name='Opsi C')),
                ('opsi_d', models.CharField(blank=True, max_length=300, verbose_name='Opsi D')),
                ('jawaban_benar', models.CharField(blank=True, help_text='A/B/C/D — kosongkan untuk soal DISC', max_length=1)),
                ('disc_a', models.CharField(blank=True, help_text='D/I/S/C', max_length=1)),
                ('disc_b', models.CharField(blank=True, max_length=1)),
                ('disc_c', models.CharField(blank=True, max_length=1)),
                ('disc_d', models.CharField(blank=True, max_length=1)),
                ('urutan', models.IntegerField(default=0, verbose_name='Urutan tampil')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Soal Bank',
                'verbose_name_plural': 'Soal Bank',
                'ordering': ['kategori', 'urutan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Rekomendasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keputusan', models.CharField(choices=[('lanjut_offering', 'Lanjut ke Offering Letter'), ('tolak', 'Tolak Kandidat'), ('hold', 'Hold / Tunda')], max_length=20)),
                ('alasan', models.TextField(blank=True, verbose_name='Alasan / Catatan')),
                ('approved_by', models.CharField(blank=True, max_length=100, verbose_name='Diputuskan oleh')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekomendasi', to='recruitment.candidate')),
            ],
            options={
                'verbose_name': 'Rekomendasi HR',
            },
        ),
        migrations.CreateModel(
            name='PsikotesSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('paket', models.JSONField(default=list, help_text='List kategori yang diujikan, e.g. ["logika","verbal","numerik","disc"]')),
                ('status', models.CharField(choices=[('pending', 'Belum Dikerjakan'), ('started', 'Sedang Dikerjakan'), ('completed', 'Selesai'), ('expired', 'Kadaluarsa')], default='pending', max_length=20)),
                ('expired_at', models.DateTimeField(default=apps.psychotest.models.default_expired)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('durasi_logika', models.IntegerField(default=15)),
                ('durasi_verbal', models.IntegerField(default=15)),
                ('durasi_numerik', models.IntegerField(default=15)),
                ('durasi_disc', models.IntegerField(default=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychotest_sessions', to='recruitment.candidate')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psychotest_sessions', to='core.company', verbose_name='Perusahaan')),
            ],
            options={
                'verbose_name': 'Sesi Psikotes',
                'verbose_name_plural': 'Sesi Psikotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PsikotesResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor_logika', models.IntegerField(blank=True, null=True)),
                ('skor_verbal', models.IntegerField(blank=True, null=True)),
                ('skor_numerik', models.IntegerField(blank=True, null=True)),
                ('skor_total', models.IntegerField(blank=True, null=True, verbose_name='Skor Total Psikotes (0-100)')),
                ('disc_d', models.IntegerField(default=0, verbose_name='DISC - Dominance')),
                ('disc_i', models.IntegerField(default=0, verbose_name='DISC - Influence')),
                ('disc_s', models.IntegerField(default=0, verbose_name='DISC - Steadiness')),
                ('disc_c', models.IntegerField(default=0, verbose_name='DISC - Conscientiousness')),
                ('disc_profil', models.CharField(blank=True, max_length=5, verbose_name='Profil DISC dominan (misal: D, IS, SC)')),
                ('disc_deskripsi', models.TextField(blank=True)),
                ('detail', models.JSONField(default=dict, verbose_name='Detail hasil (benar/salah per soal)')),
                ('catatan_hr', models.TextField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychotest_result', to='recruitment.candidate')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='psychotest.psikotessession')),
            ],
            options={
                'verbose_name': 'Hasil Psikotes',
                'verbose_name_plural': 'Hasil Psikotes',
            },
        ),
        migrations.CreateModel(
            name='OnboardingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai Kerja')),
                ('masa_probasi', models.IntegerField(default=3, verbose_name='Masa Probasi (bulan)')),
                ('doc_ktp', models.BooleanField(default=False, verbose_name='KTP')),
                ('doc_ijazah', models.BooleanField(default=False, verbose_name='Ijazah')),
                ('doc_skck', models.BooleanField(default=False, verbose_name='SKCK')),
                ('doc_foto', models.BooleanField(default=False, verbose_name='Foto 4x6')),
                ('doc_npwp', models.BooleanField(default=False, verbose_name='NPWP')),
                ('doc_bpjs', models.BooleanField(default=False, verbose_name='Kartu BPJS')),
                ('doc_rekening', models.BooleanField(default=False, verbose_name='Buku Rekening')),
                ('doc_kontrak', models.BooleanField(default=False, verbose_name='Kontrak Kerja Ditandatangani')),
                ('ori_perkenalan', models.BooleanField(default=False, verbose_name='Perkenalan Tim')),
                ('ori_sop', models.BooleanField(default=False, verbose_name='Penjelasan SOP')),
                ('ori_fasilitas', models.BooleanField(default=False, verbose_name='Pengenalan Fasilitas')),
                ('ori_sistem', models.BooleanField(default=False, verbose_name='Akses Sistem / Email')),
                ('catatan', models.TextField(blank=True)),
                ('selesai', models.BooleanField(default=False, verbose_name='Onboarding Selesai')),
                ('employee_created', models.BooleanField(default=False, verbose_name='Employee Record Dibuat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='recruitment.candidate')),
            ],
            options={
                'verbose_name': 'Onboarding Checklist',
            },
        ),
        migrations.CreateModel(
            name='MedicalCheckUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Belum MCU'), ('fit', 'Fit'), ('fit_note', 'Fit with Note'), ('unfit', 'Unfit')], default='pending', max_length=10)),
                ('tanggal_mcu', models.DateField(blank=True, null=True, verbose_name='Tanggal MCU')),
                ('faskes', models.CharField(blank=True, max_length=200, verbose_name='Fasilitas Kesehatan')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan / Diagnosis')),
                ('file_hasil', models.FileField(blank=True, null=True, upload_to='mcu/', verbose_name='File Hasil MCU')),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_checkup', to='recruitment.candidate')),
            ],
            options={
                'verbose_name': 'Medical Check Up',
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('hr', 'Interview HR'), ('user', 'Interview User / Manager'), ('final', 'Final Interview')], default='hr', max_length=10)),
                ('interviewer', models.CharField(max_length=200, verbose_name='Nama Interviewer')),
                ('tanggal', models.DateField(verbose_name='Tanggal Interview')),
                ('jam', models.TimeField(blank=True, null=True)),
                ('lokasi', models.CharField(blank=True, help_text='Ruang / Link Zoom / Google Meet', max_length=200)),
                ('nilai_technical', models.IntegerField(blank=True, null=True, verbose_name='Technical / Knowledge')),
                ('nilai_attitude', models.IntegerField(blank=True, null=True, verbose_name='Attitude')),
                ('nilai_communication', models.IntegerField(blank=True, null=True, verbose_name='Communication')),
                ('nilai_culture_fit', models.IntegerField(blank=True, null=True, verbose_name='Culture Fit')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Interviewer')),
                ('rekomendasi', models.CharField(blank=True, choices=[('lanjut', 'Lanjutkan'), ('pertimbangkan', 'Pertimbangkan'), ('tolak', 'Tolak')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='recruitment.candidate')),
            ],
            options={
                'verbose_name': 'Sesi Interview',
                'verbose_name_plural': 'Sesi Interview',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='PsikotesAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(blank=True, help_text='A/B/C/D yang dipilih kandidat', max_length=1)),
                ('disc_most', models.CharField(blank=True, max_length=1)),
                ('disc_least', models.CharField(blank=True, max_length=1)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='psychotest.psikotessession')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychotest.soalbank')),
            ],
            options={
                'verbose_name': 'Jawaban Psikotes',
                'unique_together': {('session', 'soal')},
            },
        ),
    ]
