# Generated by Django 4.2.9 on 2026-03-19 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_candidateprofile_candidateanak'),
        ('psychotest', '0002_kraepelin_and_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psikotesresult',
            name='employee',
        ),
        migrations.AlterField(
            model_name='kraepelinresult',
            name='skor_kecepatan',
            field=models.FloatField(default=0, help_text='Rata-rata kolom dikerjakan per baris'),
        ),
        migrations.AlterField(
            model_name='kraepelinresult',
            name='skor_ketahanan',
            field=models.FloatField(default=0, help_text='Perbandingan kecepatan paruh akhir vs awal'),
        ),
        migrations.AlterField(
            model_name='kraepelinresult',
            name='skor_ketelitian',
            field=models.FloatField(default=0, help_text='% jawaban benar dari yang dikerjakan'),
        ),
        migrations.AlterField(
            model_name='kraepelinresult',
            name='skor_konsistensi',
            field=models.FloatField(default=0, help_text='100 - (std_dev kecepatan / mean * 100)'),
        ),
        migrations.AlterField(
            model_name='kraepelinresult',
            name='skor_total',
            field=models.IntegerField(default=0, help_text='Skor gabungan 0-100'),
        ),
        migrations.AlterField(
            model_name='kraepelinrowresult',
            name='dikerjakan',
            field=models.IntegerField(default=0, help_text='Jumlah kolom yang dijawab'),
        ),
        migrations.AlterField(
            model_name='kraepelinsession',
            name='detik_per_baris',
            field=models.IntegerField(default=30, help_text='Detik per baris (default 30)'),
        ),
        migrations.AlterField(
            model_name='kraepelinsession',
            name='digit_per_baris',
            field=models.IntegerField(default=60, help_text='Digit per baris (default 60)'),
        ),
        migrations.AlterField(
            model_name='kraepelinsession',
            name='jumlah_baris',
            field=models.IntegerField(default=50, help_text='Jumlah baris (default 50)'),
        ),
        migrations.AlterField(
            model_name='psikotesresult',
            name='candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psychotest_result', to='recruitment.candidate'),
        ),
        migrations.AlterField(
            model_name='psikotessession',
            name='paket',
            field=models.JSONField(default=list, help_text='List kategori, e.g. ["logika","verbal","numerik","disc","kraepelin"]'),
        ),
    ]
