# Generated by Django 4.2.9 on 2026-03-20 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('assets', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(blank=True, max_length=50)),
                ('movement_date', models.DateField()),
                ('movement_type', models.CharField(choices=[('PENUGASAN', 'Penugasan'), ('PENGEMBALIAN', 'Pengembalian'), ('SERVICE', 'Service'), ('MUTASI', 'Mutasi'), ('HILANG', 'Hilang'), ('DIJUAL', 'Dijual')], max_length=20)),
                ('from_pic_name', models.CharField(blank=True, max_length=100)),
                ('from_location_name', models.CharField(blank=True, max_length=100)),
                ('from_condition', models.CharField(blank=True, max_length=50)),
                ('to_pic_name', models.CharField(blank=True, max_length=100)),
                ('to_location_name', models.CharField(blank=True, max_length=100)),
                ('to_condition', models.CharField(blank=True, max_length=50)),
                ('document_no', models.CharField(blank=True, max_length=50)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='locations.location')),
                ('from_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='employees.employee')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='locations.location')),
                ('to_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Mutasi Aset',
                'verbose_name_plural': 'Mutasi Aset',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(blank=True, max_length=50)),
                ('current_pic_name', models.CharField(blank=True, max_length=100)),
                ('current_location_name', models.CharField(blank=True, max_length=100)),
                ('current_condition', models.CharField(blank=True, max_length=50)),
                ('assignment_date', models.DateField(blank=True, null=True)),
                ('last_movement_date', models.DateField(blank=True, null=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_assignment', to='assets.asset')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_assignments', to='locations.location')),
                ('current_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_assignments', to='employees.employee')),
                ('last_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='movements.movement')),
            ],
            options={
                'verbose_name': 'Penugasan Aset',
                'verbose_name_plural': 'Penugasan Aset',
                'ordering': ['-updated_at'],
            },
        ),
    ]
