# Generated by Django 4.2.9 on 2026-03-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Shift')),
                ('kode', models.CharField(help_text='Contoh: S1, PAGI, MALAM', max_length=10, unique=True, verbose_name='Kode Shift')),
                ('tipe', models.CharField(choices=[('fixed', 'Fixed (jam tetap tiap hari)'), ('rotating', 'Rotating (bergantian antar shift)'), ('split', 'Split Shift (pagi + malam)'), ('flexible', 'Flexible / WFA (bebas, hitung durasi)')], default='fixed', max_length=10)),
                ('warna', models.CharField(default='#0d6efd', help_text='Untuk tampilan roster', max_length=7, verbose_name='Warna (hex)')),
                ('aktif', models.BooleanField(default=True)),
                ('keterangan', models.TextField(blank=True)),
                ('jam_masuk', models.TimeField(blank=True, null=True, verbose_name='Jam Masuk')),
                ('jam_keluar', models.TimeField(blank=True, null=True, verbose_name='Jam Keluar')),
                ('toleransi_telat', models.IntegerField(default=0, help_text='Menit keterlambatan yang tidak dihitung', verbose_name='Toleransi Telat (menit)')),
                ('jam_masuk_2', models.TimeField(blank=True, null=True, verbose_name='Jam Masuk Sesi 2')),
                ('jam_keluar_2', models.TimeField(blank=True, null=True, verbose_name='Jam Keluar Sesi 2')),
                ('minimal_jam_kerja', models.DecimalField(decimal_places=1, default=8, max_digits=4, verbose_name='Minimal Jam Kerja (flexible)')),
                ('hari_kerja', models.CharField(default='0,1,2,3,4', help_text='0=Senin,1=Selasa,...,6=Minggu. Pisah koma.', max_length=20, verbose_name='Hari Kerja Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.company', verbose_name='Perusahaan')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shift',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='ShiftCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='cth: Security 4-3 Pagi, Security 12Jam Rotasi', max_length=100, verbose_name='Nama Pola')),
                ('keterangan', models.TextField(blank=True)),
                ('pola_json', models.TextField(help_text='Array shift_id atau null. cth: [1,1,2,2,null,null,null]', verbose_name='Pola Shift (JSON)')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pola Shift Cyclic',
                'verbose_name_plural': 'Pola Shift Cyclic',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berlaku_mulai', models.DateField(verbose_name='Berlaku Mulai')),
                ('berlaku_sampai', models.DateField(blank=True, help_text='Kosongkan = berlaku permanen', null=True, verbose_name='Berlaku Sampai')),
                ('hari_spesifik', models.IntegerField(blank=True, choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], help_text='Kosongkan = berlaku semua hari shift', null=True, verbose_name='Hari Spesifik')),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='core.department', verbose_name='Departemen')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='employees.employee', verbose_name='Karyawan')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shifts.shift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Assignment Shift',
                'verbose_name_plural': 'Assignment Shift',
                'ordering': ['-berlaku_mulai'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeShiftCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mulai_dari', models.DateField(help_text='Hari pertama siklus dimulai untuk karyawan ini', verbose_name='Mulai Dari Tanggal')),
                ('berlaku_sampai', models.DateField(blank=True, help_text='Kosongkan = permanen', null=True, verbose_name='Berlaku Sampai')),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shifts.shiftcycle', verbose_name='Pola Shift')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_cycles', to='employees.employee', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Assignment Pola Cyclic',
                'verbose_name_plural': 'Assignment Pola Cyclic',
                'ordering': ['-mulai_dari'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('is_off', models.BooleanField(default=False, verbose_name='Hari Off/Libur')),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='employees.employee', verbose_name='Karyawan')),
                ('shift', models.ForeignKey(blank=True, help_text='Kosongkan = hari libur/off', null=True, on_delete=django.db.models.deletion.CASCADE, to='shifts.shift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Roster',
                'verbose_name_plural': 'Roster',
                'ordering': ['tanggal', 'employee__nama'],
                'unique_together': {('employee', 'tanggal')},
            },
        ),
    ]
