# Generated by Django 4.2.9 on 2026-03-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Bank')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Bank')),
                ('alias', models.CharField(blank=True, help_text='Contoh: BRI, BCA, Mandiri. Diisi otomatis dari CSV.', max_length=50, verbose_name='Alias / Singkatan')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Bank',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kabupaten/Kota')),
            ],
            options={
                'verbose_name': 'Kabupaten/Kota',
                'verbose_name_plural': 'Kabupaten/Kota',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kecamatan')),
                ('kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kecamatans', to='wilayah.kabupaten')),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Kecamatan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Provinsi')),
            ],
            options={
                'verbose_name': 'Provinsi',
                'verbose_name_plural': 'Provinsi',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kelurahan/Desa')),
                ('kode_pos', models.CharField(blank=True, max_length=10, verbose_name='Kode Pos')),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelurahans', to='wilayah.kecamatan')),
            ],
            options={
                'verbose_name': 'Kelurahan/Desa',
                'verbose_name_plural': 'Kelurahan/Desa',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='kabupaten',
            name='provinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kabupatens', to='wilayah.provinsi'),
        ),
    ]
