# Generated by Django 4.2.9 on 2026-03-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='kode',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kode Bank'),
        ),
        migrations.AlterField(
            model_name='kabupaten',
            name='kode',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kode'),
        ),
        migrations.AlterField(
            model_name='kecamatan',
            name='kode',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kode'),
        ),
        migrations.AlterField(
            model_name='kelurahan',
            name='kode',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kode'),
        ),
        migrations.AlterField(
            model_name='provinsi',
            name='kode',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kode'),
        ),
    ]
