# Generated by Django 4.2.9 on 2026-03-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_field', models.CharField(blank=True, max_length=255, verbose_name='Custom Field')),
                ('asset_name', models.CharField(max_length=200, verbose_name='Nama Asset')),
                ('tag_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customs', to='assets.category')),
            ],
            options={
                'verbose_name': 'Custom Kategori',
                'verbose_name_plural': 'Custom Kategori',
                'ordering': ['tag_number'],
            },
        ),
    ]
