# Generated by Django 4.2.9 on 2026-03-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Kandidat')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('jabatan_dilamar', models.CharField(max_length=100, verbose_name='Jabatan Dilamar')),
                ('sumber', models.CharField(blank=True, max_length=50, verbose_name='Sumber Rekrutmen')),
                ('tanggal_melamar', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Screening', 'Screening CV'), ('Psikotes', 'Psikotes'), ('Interview HR', 'Interview HR'), ('Interview User', 'Interview User'), ('Medical Check', 'Medical Check Up'), ('Offering', 'Offering Letter'), ('Hired', 'Diterima'), ('Rejected', 'Ditolak'), ('Withdrawn', 'Mundur')], default='Screening', max_length=20)),
                ('pendidikan', models.CharField(blank=True, max_length=10)),
                ('pengalaman_tahun', models.IntegerField(default=0, verbose_name='Pengalaman (tahun)')),
                ('ekspektasi_gaji', models.BigIntegerField(blank=True, null=True, verbose_name='Ekspektasi Gaji')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='File CV')),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ats_score', models.IntegerField(blank=True, null=True, verbose_name='Skor ATS')),
                ('ats_grade', models.CharField(blank=True, max_length=2, verbose_name='Grade ATS')),
                ('ats_rekomendasi', models.CharField(blank=True, max_length=20)),
                ('ats_detail', models.JSONField(blank=True, null=True, verbose_name='Detail ATS')),
                ('psikotes_score', models.IntegerField(blank=True, null=True, verbose_name='Skor Psikotes')),
                ('psikotes_grade', models.CharField(blank=True, max_length=2)),
                ('psikotes_detail', models.JSONField(blank=True, null=True)),
                ('interview_score', models.IntegerField(blank=True, null=True, verbose_name='Skor Interview')),
            ],
            options={
                'verbose_name': 'Kandidat',
                'verbose_name_plural': 'Kandidat',
                'ordering': ['-tanggal_melamar'],
            },
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(default='PT. Nama Perusahaan', max_length=200, verbose_name='Nama Perusahaan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo Perusahaan')),
                ('hrd_manager', models.CharField(blank=True, default='HRD Manager', max_length=100, verbose_name='Nama HRD Manager')),
                ('format_nomor_ol', models.CharField(default='OL/{YYYY}{MM}/{SEQ:04d}', help_text='Variabel: {YYYY}=tahun, {YY}=2digit tahun, {MM}=bulan, {DD}=hari, {SEQ}=urutan. Contoh: OL/{YYYY}/{MM}/{SEQ:04d} → OL/2025/06/0001', max_length=100, verbose_name='Format Nomor OL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Setting',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='OfferingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Template')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('is_default', models.BooleanField(default=False, verbose_name='Jadikan Default')),
                ('working_day_text', models.TextField(default='Roster Working Day, every day working including National Holiday/Red Calendar day, able to take Rest one day after two weeks work at Site, 07.30 – 16.00 (base on field working time)', verbose_name='Working Day')),
                ('employment_status_text', models.TextField(default='First Contract (PKWT I) : 6 (Six) months, If your evaluation is good/excellent, company will be consider to extend your working agreement to (PKWT II)', verbose_name='Employment Status')),
                ('meal_allowance_text', models.CharField(default='Provided by Company (breakfast, lunch, & dinner)', max_length=300, verbose_name='Meal Allowance')),
                ('residence_allowance_text', models.CharField(default='Provided by Company (mess/dormitory)', max_length=300, verbose_name='Residence Allowance')),
                ('roster_leave_text', models.CharField(default='10 : 2 (working 10 weeks)', max_length=100, verbose_name='Roster Leave')),
                ('annual_leave_text', models.CharField(default='12 months work continually, 12 working days Leave', max_length=300, verbose_name='Annual Leave')),
                ('overtime_text', models.CharField(default='Job Position Assignment Responsibility', max_length=300, verbose_name='Overtime Policy')),
                ('bpjs_kes_text', models.CharField(default='Health Care (Employee dues obligation by regulation)', max_length=300, verbose_name='BPJS Kesehatan')),
                ('bpjs_tk_text', models.CharField(default='JHT,JKK,JK,JP (JHT&JP; Employee dues obligation by regulation)', max_length=300, verbose_name='BPJS Ketenagakerjaan')),
                ('bpjs_potongan_text', models.CharField(default='Deducted 2% JHT, 1% JP, 1% Kes From Salary for BPJS TK & Kes.', max_length=300, verbose_name='Potongan BPJS')),
                ('pph21_text', models.CharField(default='Income Tax is covered by Company', max_length=300, verbose_name='PPh 21')),
                ('footer_text', models.TextField(default='The mentioned statement above as our agreement previous, so please sign the letter and submit the letter back to us as your acceptance to the term & condition in the agreement as soon as possible.\n\nThanks you for your attention and cooperation.', verbose_name='Footer Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offering Template',
                'verbose_name_plural': 'Offering Templates',
                'ordering': ['-is_default', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='OfferingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=50, unique=True, verbose_name='Nomor Surat')),
                ('jabatan', models.CharField(max_length=100)),
                ('tanggal_surat', models.DateField(verbose_name='Tanggal Surat')),
                ('tanggal_mulai_kerja', models.DateField(verbose_name='Tanggal Mulai Kerja')),
                ('site_lokasi', models.CharField(blank=True, default='', max_length=200, verbose_name='Site/Lokasi Surat')),
                ('lokasi_kerja', models.CharField(blank=True, default='', max_length=300, verbose_name='Lokasi Kerja')),
                ('point_of_hire', models.CharField(blank=True, default='', max_length=100, verbose_name='Point of Hire (POH)')),
                ('join_date_text', models.CharField(blank=True, default='As Soon As Possible', max_length=100, verbose_name='Expected Join Date')),
                ('gaji_pokok', models.BigIntegerField(verbose_name='Gaji Pokok')),
                ('fixed_allowance', models.BigIntegerField(default=0, verbose_name='Fixed Allowance')),
                ('tunjangan_total', models.BigIntegerField(default=0, verbose_name='Total Tunjangan Lain')),
                ('masa_probasi', models.IntegerField(default=3, verbose_name='Masa Probasi (bulan)')),
                ('no_arsip', models.CharField(blank=True, default='', max_length=100, verbose_name='No. Arsip')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Dikirim'), ('Accepted', 'Diterima'), ('Rejected', 'Ditolak'), ('Expired', 'Kadaluarsa')], default='Draft', max_length=20)),
                ('keterangan', models.TextField(blank=True)),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='offering_letters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_letters', to='recruitment.candidate')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.offeringtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Offering Letter',
                'verbose_name_plural': 'Offering Letter',
                'ordering': ['-tanggal_surat'],
            },
        ),
        migrations.CreateModel(
            name='ManpowerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_mprf', models.CharField(max_length=50, unique=True, verbose_name='No. MPRF')),
                ('nama_jabatan', models.CharField(max_length=100, verbose_name='Nama Jabatan')),
                ('tipe', models.CharField(choices=[('New Hire', 'Karyawan Baru'), ('Replacement', 'Pengganti'), ('Additional', 'Tambahan')], default='New Hire', max_length=20)),
                ('jumlah_kebutuhan', models.IntegerField(default=1, verbose_name='Jumlah Kebutuhan')),
                ('alasan', models.TextField(verbose_name='Alasan Kebutuhan')),
                ('kualifikasi', models.TextField(blank=True, verbose_name='Kualifikasi')),
                ('target_date', models.DateField(verbose_name='Target Pengisian')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Disetujui'), ('Open', 'Dibuka'), ('In Process', 'Dalam Proses'), ('Filled', 'Terpenuhi'), ('Cancelled', 'Dibatalkan')], default='Draft', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mprfs', to='core.company', verbose_name='Perusahaan')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.position')),
            ],
            options={
                'verbose_name': 'Manpower Request',
                'verbose_name_plural': 'Manpower Request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='mprf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.manpowerrequest'),
        ),
    ]
