# Generated by Django 4.2.9 on 2026-03-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Diisi otomatis dari MPRF atau saat tambah manual.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.company', verbose_name='Perusahaan'),
        ),
    ]
