# Generated by Django 4.2.9 on 2026-03-20 13:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nik', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIK')),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('admin', 'Admin'), ('hr_manager', 'HR Manager'), ('hr_staff', 'HR Staff'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Perusahaan')),
                ('singkatan', models.CharField(blank=True, max_length=20, verbose_name='Singkatan')),
                ('slug', models.SlugField(help_text='Identifier unik. Contoh: pt-maju-jaya', max_length=80, unique=True, verbose_name='Slug')),
                ('npwp', models.CharField(blank=True, max_length=25, verbose_name='NPWP')),
                ('alamat', models.TextField(blank=True, verbose_name='Alamat')),
                ('no_telp', models.CharField(blank=True, max_length=20, verbose_name='No. Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('trial', 'Trial'), ('demo', 'Demo'), ('suspend', 'Suspend'), ('nonaktif', 'Nonaktif')], default='trial', max_length=10)),
                ('tanggal_daftar', models.DateField(auto_now_add=True, verbose_name='Tanggal Daftar')),
                ('trial_sampai', models.DateField(blank=True, null=True, verbose_name='Trial Sampai')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Internal')),
                ('demo_reset_schedule', models.CharField(choices=[('daily', 'Setiap Hari (00:00)'), ('weekly', 'Setiap Minggu (Senin 00:00)')], default='daily', help_text='Hanya berlaku jika status = Demo', max_length=10, verbose_name='Jadwal Reset Demo')),
                ('last_demo_reset', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Reset Demo')),
                ('pic_nama', models.CharField(blank=True, max_length=100, verbose_name='Nama PIC')),
                ('pic_no_hp', models.CharField(blank=True, max_length=20, verbose_name='No HP / WhatsApp PIC')),
                ('paket', models.CharField(choices=[('starter', 'Starter (s/d 100 karyawan)'), ('professional', 'Professional (s/d 300 karyawan)'), ('pro_full', 'Pro Full (s/d 500 karyawan)'), ('enterprise', 'Enterprise (Unlimited)')], default='starter', help_text='Paket yang diambil oleh tenant ini', max_length=20, verbose_name='Paket Langganan')),
                ('enforce_limit', models.BooleanField(default=False, help_text='OFF = unlimited (untuk testing/demo). ON = batas karyawan berlaku sesuai paket.', verbose_name='Aktifkan Batas Karyawan')),
                ('addon_assets', models.BooleanField(default=False, verbose_name='Add-On: Asset Management')),
                ('addon_recruitment', models.BooleanField(default=False, verbose_name='Add-On: Rekrutmen')),
                ('addon_psychotest', models.BooleanField(default=False, verbose_name='Add-On: Psikotes')),
                ('addon_advanced_psychotest', models.BooleanField(default=False, verbose_name='Add-On: Advanced Psychotest (OCEAN)')),
                ('addon_od', models.BooleanField(default=False, verbose_name='Add-On: Organisation Development')),
                ('addon_performance', models.BooleanField(default=False, verbose_name='Add-On: Performance & KPI')),
                ('nama_penandatangan_default', models.CharField(blank=True, max_length=100, verbose_name='Nama Penandatangan Default')),
                ('jabatan_penandatangan_default', models.CharField(blank=True, max_length=100, verbose_name='Jabatan Penandatangan Default')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude Kantor Pusat')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude Kantor Pusat')),
                ('radius_meter', models.PositiveIntegerField(blank=True, help_text='Fallback jika Job Site tidak punya koordinat.', null=True, verbose_name='Radius Check-In Kantor Pusat (meter)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perusahaan (Tenant)',
                'verbose_name_plural': 'Perusahaan (Tenant)',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Departemen')),
                ('kode', models.CharField(blank=True, max_length=20)),
                ('deskripsi', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.company', verbose_name='Perusahaan')),
            ],
            options={
                'verbose_name': 'Departemen',
                'verbose_name_plural': 'Departemen',
                'ordering': ['nama'],
                'unique_together': {('company', 'nama')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Crew', 'Crew'), ('Jr.Staff', 'Jr.Staff'), ('Staff', 'Staff'), ('Sr.Staff', 'Sr.Staff'), ('Jr.Supervisor', 'Jr.Supervisor'), ('Supervisor', 'Supervisor'), ('Sr.Supervisor', 'Sr.Supervisor'), ('Jr.Superintendent', 'Jr.Superintendent'), ('Superintendent', 'Superintendent'), ('Sr.Superintendent', 'Sr.Superintendent'), ('Jr.Manager', 'Jr.Manager'), ('Manager', 'Manager'), ('Sr.Manager', 'Sr.Manager'), ('Manajemen', 'Manajemen'), ('Corporate Manajemen', 'Corporate Manajemen')], default='Staff', max_length=50)),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi Jabatan')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_desc', models.TextField(blank=True, verbose_name='Job Description')),
                ('skill_wajib', models.TextField(blank=True, verbose_name='Skill Wajib')),
                ('skill_diinginkan', models.TextField(blank=True, verbose_name='Skill Diinginkan')),
                ('pendidikan_min', models.CharField(blank=True, choices=[('', 'Tidak Ditentukan'), ('SD', 'SD'), ('SMP', 'SMP'), ('SMA/SMK', 'SMA/SMK'), ('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], default='', max_length=10)),
                ('pengalaman_min', models.IntegerField(default=0, verbose_name='Pengalaman Minimum (tahun)')),
                ('bobot_skill_wajib', models.IntegerField(default=40)),
                ('bobot_pengalaman', models.IntegerField(default=25)),
                ('bobot_pendidikan', models.IntegerField(default=20)),
                ('bobot_skill_tambahan', models.IntegerField(default=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.company', verbose_name='Perusahaan')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('parent', models.ForeignKey(blank=True, help_text='Jabatan yang menjadi atasan langsung. Kosong = pucuk hierarki.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.position', verbose_name='Atasan Jabatan')),
            ],
            options={
                'verbose_name': 'Jabatan',
                'verbose_name_plural': 'Jabatan',
                'ordering': ['nama'],
                'unique_together': {('company', 'nama')},
            },
        ),
        migrations.CreateModel(
            name='OrgChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Org Chart')),
                ('periode', models.CharField(max_length=7, verbose_name='Periode (YYYY)')),
                ('berlaku_mulai', models.DateField(verbose_name='Berlaku Mulai')),
                ('berlaku_sampai', models.DateField(blank=True, null=True, verbose_name='Berlaku Sampai')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('aktif', 'Aktif'), ('arsip', 'Diarsipkan')], default='draft', max_length=10)),
                ('deskripsi', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_charts', to='core.company', verbose_name='Perusahaan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_charts_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Org Chart',
                'verbose_name_plural': 'Org Charts',
                'ordering': ['-berlaku_mulai'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Perusahaan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.company', verbose_name='Perusahaan'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='jabatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.position'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='ApprovalMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modul', models.CharField(choices=[('leave', 'Cuti / Izin'), ('overtime', 'Lembur'), ('payroll', 'Payroll'), ('performance', 'Penilaian Kinerja'), ('movement', 'Mutasi / Promosi'), ('recruitment', 'Rekrutmen / MPP'), ('contract', 'Kontrak Kerja'), ('sp', 'Surat Peringatan'), ('phk', 'Pemutusan Hubungan Kerja')], max_length=30, verbose_name='Modul')),
                ('level_approval', models.PositiveSmallIntegerField(default=1, help_text='1 = approval pertama, dst.', verbose_name='Level Approval')),
                ('auto_approve_hari', models.PositiveSmallIntegerField(default=0, help_text='0 = tidak auto.', verbose_name='Auto-Approve (hari)')),
                ('notif_email', models.BooleanField(default=True, verbose_name='Kirim Notif Email')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_matrices', to='core.company', verbose_name='Perusahaan')),
                ('jabatan_approver', models.ForeignKey(blank=True, help_text='Kosong = auto-derive dari Position.parent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_sebagai_approver', to='core.position', verbose_name='Jabatan Approver')),
                ('jabatan_pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_sebagai_pemohon', to='core.position', verbose_name='Jabatan Pemohon')),
            ],
            options={
                'verbose_name': 'Approval Matrix',
                'verbose_name_plural': 'Approval Matrix',
                'ordering': ['modul', 'jabatan_pemohon', 'level_approval'],
                'unique_together': {('company', 'modul', 'jabatan_pemohon', 'level_approval')},
            },
        ),
    ]
