# Generated by Django 4.2.9 on 2026-03-12 12:37

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nik', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIK')),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('admin', 'Admin'), ('hr_manager', 'HR Manager'), ('hr_staff', 'HR Staff'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Perusahaan')),
                ('singkatan', models.CharField(blank=True, max_length=20, verbose_name='Singkatan')),
                ('slug', models.SlugField(help_text='Identifier unik. Contoh: pt-maju-jaya', max_length=80, unique=True, verbose_name='Slug')),
                ('npwp', models.CharField(blank=True, max_length=25, verbose_name='NPWP')),
                ('alamat', models.TextField(blank=True, verbose_name='Alamat')),
                ('no_telp', models.CharField(blank=True, max_length=20, verbose_name='No. Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('trial', 'Trial'), ('suspend', 'Suspend'), ('nonaktif', 'Nonaktif')], default='trial', max_length=10)),
                ('tanggal_daftar', models.DateField(auto_now_add=True, verbose_name='Tanggal Daftar')),
                ('trial_sampai', models.DateField(blank=True, null=True, verbose_name='Trial Sampai')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Internal')),
                ('addon_assets', models.BooleanField(default=False, verbose_name='Add-On: Asset Management')),
                ('addon_recruitment', models.BooleanField(default=False, verbose_name='Add-On: Rekrutmen')),
                ('addon_psychotest', models.BooleanField(default=False, verbose_name='Add-On: Psikotes')),
                ('addon_advanced_psychotest', models.BooleanField(default=False, verbose_name='Add-On: Advanced Psychotest (OCEAN)')),
                ('addon_od', models.BooleanField(default=False, verbose_name='Add-On: Organisation Development')),
                ('nama_penandatangan_default', models.CharField(blank=True, help_text='Auto-fill ke form SP, PB, Kontrak, SKK, Surat PHK.', max_length=100, verbose_name='Nama Penandatangan Default')),
                ('jabatan_penandatangan_default', models.CharField(blank=True, help_text='Auto-fill ke form SP, PB, Kontrak, SKK, Surat PHK.', max_length=100, verbose_name='Jabatan Penandatangan Default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perusahaan (Tenant)',
                'verbose_name_plural': 'Perusahaan (Tenant)',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Departemen')),
                ('kode', models.CharField(blank=True, max_length=20)),
                ('deskripsi', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.company', verbose_name='Perusahaan')),
            ],
            options={
                'verbose_name': 'Departemen',
                'verbose_name_plural': 'Departemen',
                'ordering': ['nama'],
                'unique_together': {('company', 'nama')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Staff', 'Staff'), ('Senior Staff', 'Senior Staff'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Senior Manager', 'Senior Manager'), ('General Manager', 'General Manager'), ('Director', 'Director')], default='Staff', max_length=50)),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi Jabatan')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_desc', models.TextField(blank=True, verbose_name='Job Description')),
                ('skill_wajib', models.TextField(blank=True, verbose_name='Skill Wajib')),
                ('skill_diinginkan', models.TextField(blank=True, verbose_name='Skill Diinginkan')),
                ('pendidikan_min', models.CharField(blank=True, choices=[('', 'Tidak Ditentukan'), ('SD', 'SD'), ('SMP', 'SMP'), ('SMA/SMK', 'SMA/SMK'), ('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], default='', max_length=10)),
                ('pengalaman_min', models.IntegerField(default=0, verbose_name='Pengalaman Minimum (tahun)')),
                ('bobot_skill_wajib', models.IntegerField(default=40)),
                ('bobot_pengalaman', models.IntegerField(default=25)),
                ('bobot_pendidikan', models.IntegerField(default=20)),
                ('bobot_skill_tambahan', models.IntegerField(default=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.company', verbose_name='Perusahaan')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
            ],
            options={
                'verbose_name': 'Jabatan',
                'verbose_name_plural': 'Jabatan',
                'ordering': ['nama'],
                'unique_together': {('company', 'nama')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Perusahaan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Kosongkan hanya untuk Developer (superuser Django).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.company', verbose_name='Perusahaan'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='jabatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.position'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
