# Generated by Django 4.2.9 on 2026-03-13 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Jabatan yang menjadi atasan langsung. Kosong = pucuk hierarki.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.position', verbose_name='Atasan Jabatan'),
        ),
        migrations.AlterField(
            model_name='company',
            name='jabatan_penandatangan_default',
            field=models.CharField(blank=True, max_length=100, verbose_name='Jabatan Penandatangan Default'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nama_penandatangan_default',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama Penandatangan Default'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.company', verbose_name='Perusahaan'),
        ),
        migrations.CreateModel(
            name='OrgChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Org Chart')),
                ('periode', models.CharField(max_length=7, verbose_name='Periode (YYYY)')),
                ('berlaku_mulai', models.DateField(verbose_name='Berlaku Mulai')),
                ('berlaku_sampai', models.DateField(blank=True, null=True, verbose_name='Berlaku Sampai')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('aktif', 'Aktif'), ('arsip', 'Diarsipkan')], default='draft', max_length=10)),
                ('deskripsi', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_charts', to='core.company', verbose_name='Perusahaan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_charts_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Org Chart',
                'verbose_name_plural': 'Org Charts',
                'ordering': ['-berlaku_mulai'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modul', models.CharField(choices=[('leave', 'Cuti / Izin'), ('overtime', 'Lembur'), ('payroll', 'Payroll'), ('performance', 'Penilaian Kinerja'), ('movement', 'Mutasi / Promosi'), ('recruitment', 'Rekrutmen / MPP'), ('contract', 'Kontrak Kerja'), ('sp', 'Surat Peringatan'), ('phk', 'Pemutusan Hubungan Kerja')], max_length=30, verbose_name='Modul')),
                ('level_approval', models.PositiveSmallIntegerField(default=1, help_text='1 = approval pertama, dst.', verbose_name='Level Approval')),
                ('auto_approve_hari', models.PositiveSmallIntegerField(default=0, help_text='0 = tidak auto.', verbose_name='Auto-Approve (hari)')),
                ('notif_email', models.BooleanField(default=True, verbose_name='Kirim Notif Email')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_matrices', to='core.company', verbose_name='Perusahaan')),
                ('jabatan_approver', models.ForeignKey(blank=True, help_text='Kosong = auto-derive dari Position.parent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_sebagai_approver', to='core.position', verbose_name='Jabatan Approver')),
                ('jabatan_pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_sebagai_pemohon', to='core.position', verbose_name='Jabatan Pemohon')),
            ],
            options={
                'verbose_name': 'Approval Matrix',
                'verbose_name_plural': 'Approval Matrix',
                'ordering': ['modul', 'jabatan_pemohon', 'level_approval'],
                'unique_together': {('company', 'modul', 'jabatan_pemohon', 'level_approval')},
            },
        ),
    ]
