# Generated by Django 4.2.9 on 2026-03-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon', models.CharField(choices=[('assets', 'Asset Management'), ('recruitment', 'Rekrutmen'), ('psychotest', 'Psikotes'), ('advanced_psychotest', 'Advanced Psychotest (OCEAN)'), ('od', 'Organisation Development'), ('performance', 'Performance & KPI')], max_length=30)),
                ('serial_key', models.CharField(max_length=100, verbose_name='Serial Key')),
                ('expiry', models.DateField(blank=True, help_text='NULL = Lifetime', null=True, verbose_name='Tanggal Expired')),
                ('aktif', models.BooleanField(default=True)),
                ('diaktifkan_oleh', models.CharField(blank=True, max_length=100)),
                ('aktif_sejak', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_licenses', to='core.company')),
            ],
            options={
                'verbose_name': 'Addon License',
                'verbose_name_plural': 'Addon Licenses',
                'ordering': ['company', 'addon'],
                'unique_together': {('company', 'addon')},
            },
        ),
    ]
