# Generated by Django 4.2.9 on 2026-03-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_addonlicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonlicense',
            name='addon',
            field=models.CharField(choices=[('assets', 'Asset Management'), ('recruitment', 'Rekrutmen'), ('psychotest', 'Psikotes'), ('advanced_psychotest', 'Advanced Psychotest (OCEAN)'), ('od', 'Organisation Development')], max_length=30),
        ),
    ]
