# Generated by Django 4.2.9 on 2026-03-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_position_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='demo_reset_schedule',
            field=models.CharField(choices=[('daily', 'Setiap Hari (00:00)'), ('weekly', 'Setiap Minggu (Senin 00:00)')], default='daily', help_text='Hanya berlaku jika status = Demo', max_length=10, verbose_name='Jadwal Reset Demo'),
        ),
        migrations.AddField(
            model_name='company',
            name='last_demo_reset',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Reset Demo'),
        ),
        migrations.AddField(
            model_name='company',
            name='pic_nama',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama PIC'),
        ),
        migrations.AddField(
            model_name='company',
            name='pic_no_hp',
            field=models.CharField(blank=True, max_length=20, verbose_name='No HP / WhatsApp PIC'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('trial', 'Trial'), ('demo', 'Demo'), ('suspend', 'Suspend'), ('nonaktif', 'Nonaktif')], default='trial', max_length=10),
        ),
    ]
