# Generated by Django 4.2.9 on 2026-03-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_demo_reset_schedule_company_last_demo_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='addon_performance',
            field=models.BooleanField(default=False, verbose_name='Add-On: Performance & KPI'),
        ),
        migrations.AddField(
            model_name='company',
            name='enforce_limit',
            field=models.BooleanField(default=False, help_text='OFF = unlimited (untuk testing/demo). ON = batas karyawan berlaku sesuai paket.', verbose_name='Aktifkan Batas Karyawan'),
        ),
        migrations.AddField(
            model_name='company',
            name='paket',
            field=models.CharField(choices=[('starter', 'Starter (s/d 100 karyawan)'), ('professional', 'Professional (s/d 300 karyawan)'), ('pro_full', 'Pro Full (s/d 500 karyawan)'), ('enterprise', 'Enterprise (Unlimited)')], default='starter', help_text='Paket yang diambil oleh tenant ini', max_length=20, verbose_name='Paket Langganan'),
        ),
    ]
