# Generated by Django 4.2.9 on 2026-03-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_addon_performance_company_enforce_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='level',
            field=models.CharField(choices=[('Crew', 'Crew'), ('Jr.Staff', 'Jr.Staff'), ('Staff', 'Staff'), ('Sr.Staff', 'Sr.Staff'), ('Jr.Supervisor', 'Jr.Supervisor'), ('Supervisor', 'Supervisor'), ('Sr.Supervisor', 'Sr.Supervisor'), ('Jr.Superintendent', 'Jr.Superintendent'), ('Superintendent', 'Superintendent'), ('Sr.Superintendent', 'Sr.Superintendent'), ('Jr.Manager', 'Jr.Manager'), ('Manager', 'Manager'), ('Sr.Manager', 'Sr.Manager'), ('Manajemen', 'Manajemen'), ('Corporate Manajemen', 'Corporate Manajemen')], default='Staff', max_length=50),
        ),
    ]
