# Generated by Django 4.2.9 on 2026-03-20 13:57

import apps.advanced_psychotest.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(blank=True, help_text='A/B/C/D untuk PG; 1-5 untuk Likert', max_length=1)),
                ('sjt_ranking', models.CharField(blank=True, max_length=20)),
                ('likert_val', models.IntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('raven', "Raven's Progressive Matrices"), ('cogspeed', 'Cognitive Speed Test'), ('bigfive', 'Big Five Personality (OCEAN)'), ('sjt', 'Situational Judgement Test'), ('cfit', 'Culture Fair Intelligence Test')], max_length=20)),
                ('skor_total', models.IntegerField(blank=True, null=True)),
                ('percentile', models.IntegerField(blank=True, help_text='Percentile vs norma populasi (estimasi)', null=True)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('ocean_o', models.IntegerField(blank=True, null=True, verbose_name='Openness')),
                ('ocean_c', models.IntegerField(blank=True, null=True, verbose_name='Conscientiousness')),
                ('ocean_e', models.IntegerField(blank=True, null=True, verbose_name='Extraversion')),
                ('ocean_a', models.IntegerField(blank=True, null=True, verbose_name='Agreeableness')),
                ('ocean_n', models.IntegerField(blank=True, null=True, verbose_name='Neuroticism')),
                ('detail', models.JSONField(default=dict)),
                ('interpretasi', models.TextField(blank=True)),
                ('catatan_hr', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hasil Advanced Test',
                'verbose_name_plural': 'Hasil Advanced Test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tujuan', models.CharField(blank=True, default='recruitment', max_length=20)),
                ('paket', models.JSONField(default=list, help_text='List tipe tes dalam sesi ini, e.g. ["raven","cogspeed"]')),
                ('test_type', models.CharField(blank=True, choices=[('raven', "Raven's Progressive Matrices"), ('cogspeed', 'Cognitive Speed Test'), ('bigfive', 'Big Five Personality (OCEAN)'), ('sjt', 'Situational Judgement Test'), ('cfit', 'Culture Fair Intelligence Test')], max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Belum Dikerjakan'), ('started', 'Sedang Dikerjakan'), ('completed', 'Selesai'), ('expired', 'Kadaluarsa')], default='pending', max_length=20)),
                ('durasi_per_tes', models.JSONField(blank=True, default=dict)),
                ('durasi_menit', models.IntegerField(default=25, verbose_name='Durasi (menit)')),
                ('tipe_started_at', models.JSONField(blank=True, default=dict)),
                ('expired_at', models.DateTimeField(default=apps.advanced_psychotest.models.default_expired_adv)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sesi Advanced Test',
                'verbose_name_plural': 'Sesi Advanced Test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('raven', "Raven's Progressive Matrices"), ('cogspeed', 'Cognitive Speed Test'), ('bigfive', 'Big Five Personality (OCEAN)'), ('sjt', 'Situational Judgement Test'), ('cfit', 'Culture Fair Intelligence Test')], max_length=20)),
                ('tipe_soal', models.CharField(choices=[('pilihan_ganda', 'Pilihan Ganda (satu jawaban benar)'), ('likert', 'Likert Scale 1-5 (Big Five)'), ('sjt_rank', 'SJT Ranking (urutkan respons)'), ('best_worst', 'Best / Worst (pilih terbaik & terburuk)')], default='pilihan_ganda', max_length=20)),
                ('nomor', models.IntegerField(default=1, verbose_name='Nomor Soal')),
                ('pertanyaan', models.TextField(verbose_name='Pertanyaan / Deskripsi Situasi')),
                ('opsi_a', models.TextField(blank=True, verbose_name='Opsi A')),
                ('opsi_b', models.TextField(blank=True, verbose_name='Opsi B')),
                ('opsi_c', models.TextField(blank=True, verbose_name='Opsi C')),
                ('opsi_d', models.TextField(blank=True, verbose_name='Opsi D')),
                ('opsi_e', models.TextField(blank=True, verbose_name='Opsi E (Likert ke-5)')),
                ('jawaban_benar', models.CharField(blank=True, help_text='A/B/C/D — kosong untuk likert/sjt_rank', max_length=1)),
                ('bigfive_dimensi', models.CharField(blank=True, choices=[('O', 'Openness'), ('C', 'Conscientiousness'), ('E', 'Extraversion'), ('A', 'Agreeableness'), ('N', 'Neuroticism')], help_text='Khusus Big Five', max_length=1)),
                ('bigfive_reverse', models.BooleanField(default=False, help_text='Reverse-scored item')),
                ('sjt_skor_a', models.IntegerField(default=0)),
                ('sjt_skor_b', models.IntegerField(default=0)),
                ('sjt_skor_c', models.IntegerField(default=0)),
                ('sjt_skor_d', models.IntegerField(default=0)),
                ('tingkat_kesulitan', models.CharField(choices=[('mudah', 'Mudah'), ('sedang', 'Sedang'), ('sulit', 'Sulit')], default='sedang', max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Soal Advanced',
                'verbose_name_plural': 'Bank Soal Advanced',
                'ordering': ['test_type', 'nomor'],
            },
        ),
    ]
