# Generated by Django 4.2.9 on 2026-03-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment', '0001_initial'),
        ('employees', '0001_initial'),
        ('advanced_psychotest', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advsession',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adv_sessions', to='recruitment.candidate'),
        ),
        migrations.AddField(
            model_name='advsession',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adv_sessions', to='core.company', verbose_name='Perusahaan'),
        ),
        migrations.AddField(
            model_name='advsession',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adv_sessions', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='advresult',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adv_results', to='recruitment.candidate'),
        ),
        migrations.AddField(
            model_name='advresult',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adv_results', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='advresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='advanced_psychotest.advsession'),
        ),
        migrations.AddField(
            model_name='advanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='advanced_psychotest.advsession'),
        ),
        migrations.AddField(
            model_name='advanswer',
            name='soal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advanced_psychotest.advsoal'),
        ),
        migrations.AlterUniqueTogether(
            name='advresult',
            unique_together={('session', 'test_type')},
        ),
        migrations.AlterUniqueTogether(
            name='advanswer',
            unique_together={('session', 'soal')},
        ),
    ]
