# Generated by Django 4.2.9 on 2026-03-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenilaianKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submit', 'Diajukan'), ('review', 'Dalam Review Atasan'), ('approved', 'Disetujui'), ('rejected', 'Dikembalikan')], default='draft', max_length=10)),
                ('catatan_karyawan', models.TextField(blank=True, verbose_name='Catatan Karyawan')),
                ('catatan_atasan', models.TextField(blank=True, verbose_name='Catatan Atasan')),
                ('skor_kpi', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Skor KPI (%)')),
                ('skor_review', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Skor Review Atasan (%)')),
                ('skor_akhir', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Skor Akhir (%)')),
                ('predikat', models.CharField(blank=True, max_length=30, verbose_name='Predikat')),
                ('tanggal_submit', models.DateTimeField(blank=True, null=True)),
                ('tanggal_approve', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atasan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penilaian_sebagai_atasan', to='employees.employee', verbose_name='Penilai / Atasan')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Penilaian Karyawan',
                'verbose_name_plural': 'Penilaian Karyawan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeriodePenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Periode')),
                ('tipe', models.CharField(choices=[('Bulanan', 'Bulanan'), ('Triwulan', 'Triwulan (Q)'), ('Semesteran', 'Semesteran'), ('Tahunan', 'Tahunan')], default='Tahunan', max_length=15)),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(verbose_name='Tanggal Selesai')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('aktif', 'Aktif'), ('tutup', 'Ditutup')], default='draft', max_length=10)),
                ('deskripsi', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periode_penilaian', to='core.company')),
            ],
            options={
                'verbose_name': 'Periode Penilaian',
                'verbose_name_plural': 'Periode Penilaian',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAtasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspek', models.CharField(help_text='Misal: Kedisiplinan, Komunikasi, Teamwork', max_length=100, verbose_name='Aspek Penilaian')),
                ('bobot', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Bobot (%)')),
                ('skor', models.IntegerField(blank=True, choices=[(1, '1 — Sangat Kurang'), (2, '2 — Kurang'), (3, '3 — Cukup'), (4, '4 — Baik'), (5, '5 — Sangat Baik')], null=True)),
                ('catatan', models.TextField(blank=True)),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='performance.penilaiankaryawan')),
            ],
            options={
                'verbose_name': 'Review Atasan',
                'verbose_name_plural': 'Review Atasan',
            },
        ),
        migrations.CreateModel(
            name='Review360Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('aktif', 'Aktif — Menunggu Reviewer'), ('selesai', 'Selesai'), ('batal', 'Dibatalkan')], default='draft', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Batas Waktu Pengisian')),
                ('skor_atasan', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('skor_rekan', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('skor_bawahan', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('skor_self', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('skor_360', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Skor 360° (Gabungan)')),
                ('predikat', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review360_sessions', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review360_as_subject', to='employees.employee', verbose_name='Karyawan yang Dinilai')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review360_sessions', to='performance.periodepenilaian')),
            ],
            options={
                'verbose_name': 'Sesi Review 360°',
                'verbose_name_plural': 'Sesi Review 360°',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='Review360Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('self', 'Self-Assessment'), ('atasan', 'Atasan'), ('rekan', 'Rekan Sejawat'), ('bawahan', 'Bawahan')], max_length=10, verbose_name='Tipe Hubungan')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Sudah Diisi')),
                ('tanggal_submit', models.DateTimeField(blank=True, null=True)),
                ('catatan_umum', models.TextField(blank=True, verbose_name='Catatan / Feedback Umum')),
                ('skor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Skor Total (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review360_as_reviewer', to='employees.employee', verbose_name='Reviewer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.review360session')),
            ],
            options={
                'verbose_name': 'Reviewer 360°',
                'verbose_name_plural': 'Reviewer 360°',
                'ordering': ['tipe', 'reviewer__nama'],
                'unique_together': {('session', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='Review360Aspek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Aspek / Pertanyaan')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Panduan Penilaian')),
                ('tipe_reviewer', models.CharField(choices=[('semua', 'Semua Tipe Reviewer'), ('atasan', 'Hanya Atasan'), ('rekan', 'Rekan & Bawahan'), ('self', 'Hanya Self')], default='semua', max_length=10, verbose_name='Ditampilkan ke')),
                ('bobot', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Bobot (%)')),
                ('urutan', models.IntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review360_aspek', to='core.company')),
            ],
            options={
                'verbose_name': 'Aspek Review 360°',
                'verbose_name_plural': 'Aspek Review 360°',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.AddField(
            model_name='penilaiankaryawan',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian', to='performance.periodepenilaian'),
        ),
        migrations.CreateModel(
            name='KPITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Indikator')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('satuan', models.CharField(choices=[('%', 'Persentase (%)'), ('angka', 'Angka'), ('rupiah', 'Rupiah (Rp)'), ('hari', 'Hari'), ('jam', 'Jam'), ('unit', 'Unit'), ('lainnya', 'Lainnya')], default='%', max_length=10)),
                ('arah', models.CharField(choices=[('tinggi', 'Semakin Tinggi Semakin Baik'), ('rendah', 'Semakin Rendah Semakin Baik')], default='tinggi', max_length=10, verbose_name='Arah Penilaian')),
                ('kategori', models.CharField(blank=True, help_text='Misal: Keuangan, Pelanggan, Proses, SDM', max_length=100, verbose_name='Kategori/Perspektif')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_templates', to='core.company')),
            ],
            options={
                'verbose_name': 'Template KPI',
                'verbose_name_plural': 'Template KPI',
                'ordering': ['kategori', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='KPIItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kpi', models.CharField(max_length=200, verbose_name='Nama KPI')),
                ('satuan', models.CharField(default='%', max_length=10)),
                ('arah', models.CharField(default='tinggi', max_length=10)),
                ('bobot', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Bobot (%)')),
                ('target', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Target')),
                ('realisasi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Realisasi')),
                ('catatan', models.TextField(blank=True)),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_items', to='performance.penilaiankaryawan')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_items', to='performance.kpitemplate')),
            ],
            options={
                'verbose_name': 'KPI Item',
                'verbose_name_plural': 'KPI Items',
                'ordering': ['nama_kpi'],
            },
        ),
        migrations.CreateModel(
            name='Review360AnswerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.IntegerField(blank=True, choices=[(1, '1 — Sangat Kurang'), (2, '2 — Kurang'), (3, '3 — Cukup'), (4, '4 — Baik'), (5, '5 — Sangat Baik')], null=True)),
                ('catatan', models.TextField(blank=True)),
                ('aspek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='performance.review360aspek')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_items', to='performance.review360reviewer')),
            ],
            options={
                'verbose_name': 'Jawaban Review 360°',
                'verbose_name_plural': 'Jawaban Review 360°',
                'unique_together': {('reviewer', 'aspek')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='penilaiankaryawan',
            unique_together={('employee', 'periode')},
        ),
    ]
