# Generated by Django 4.2.9 on 2026-03-12 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiodataChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field')),
                ('label', models.CharField(max_length=100, verbose_name='Label Field')),
                ('nilai_lama', models.TextField(blank=True, verbose_name='Nilai Lama')),
                ('nilai_baru', models.TextField(blank=True, verbose_name='Nilai Baru')),
                ('waktu', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Perubahan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biodata_logs', to='employees.employee', verbose_name='Karyawan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diubah oleh')),
            ],
            options={
                'verbose_name': 'Log Perubahan Biodata',
                'verbose_name_plural': 'Log Perubahan Biodata',
                'ordering': ['-waktu'],
            },
        ),
    ]
