# Generated by Django 4.2.9 on 2026-03-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, choices=[('Gedung', 'Gedung'), ('Lantai', 'Lantai'), ('Ruangan', 'Ruangan'), ('Gudang', 'Gudang'), ('Area', 'Area'), ('Rak', 'Rak'), ('Lemari', 'Lemari'), ('Lainnya', 'Lainnya')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.location')),
            ],
            options={
                'verbose_name': 'Lokasi',
                'verbose_name_plural': 'Lokasi',
                'ordering': ['code'],
            },
        ),
    ]
