# Generated by Django 4.2.9 on 2026-03-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, verbose_name='Kode')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Kompetensi')),
                ('deskripsi', models.TextField(blank=True)),
                ('level_1_desc', models.TextField(blank=True, verbose_name='Deskripsi Level 1 (Dasar)')),
                ('level_2_desc', models.TextField(blank=True, verbose_name='Deskripsi Level 2 (Berkembang)')),
                ('level_3_desc', models.TextField(blank=True, verbose_name='Deskripsi Level 3 (Kompeten)')),
                ('level_4_desc', models.TextField(blank=True, verbose_name='Deskripsi Level 4 (Mahir)')),
                ('level_5_desc', models.TextField(blank=True, verbose_name='Deskripsi Level 5 (Ahli/Expert)')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='core.company')),
            ],
            options={
                'verbose_name': 'Kompetensi',
                'verbose_name_plural': 'Kompetensi',
                'ordering': ['kategori', 'kode'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(help_text='Contoh: 2026', max_length=7, verbose_name='Periode (YYYY)')),
                ('tanggal_rencana', models.DateField(blank=True, null=True, verbose_name='Tanggal Rencana Pelaksanaan')),
                ('status', models.CharField(choices=[('rencana', 'Direncanakan'), ('disetujui', 'Disetujui'), ('berjalan', 'Sedang Berjalan'), ('selesai', 'Selesai'), ('batal', 'Dibatalkan')], default='rencana', max_length=10)),
                ('prioritas', models.IntegerField(choices=[(1, 'Tinggi'), (2, 'Sedang'), (3, 'Rendah')], default=2, verbose_name='Prioritas')),
                ('alasan', models.TextField(blank=True, verbose_name='Alasan / Kebutuhan Training')),
                ('tanggal_disetujui', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='core.company')),
                ('disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plans_disetujui', to='employees.employee', verbose_name='Disetujui Oleh')),
                ('diusulkan_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plans_diusulkan', to='employees.employee', verbose_name='Diusulkan Oleh')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='employees.employee', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Rencana Training',
                'verbose_name_plural': 'Rencana Training',
                'ordering': ['periode', 'prioritas', 'employee__nama'],
            },
        ),
        migrations.CreateModel(
            name='WorkloadStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aktivitas', models.CharField(max_length=200, verbose_name='Nama Aktivitas / Beban Kerja')),
                ('standar_output', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Standar Output')),
                ('satuan', models.CharField(choices=[('jam/hari', 'Jam per Hari'), ('jam/minggu', 'Jam per Minggu'), ('unit/hari', 'Unit per Hari'), ('unit/bulan', 'Unit per Bulan')], default='jam/hari', max_length=15)),
                ('deskripsi', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_standards', to='core.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workload_standards', to='core.department')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_standards', to='core.position', verbose_name='Jabatan')),
            ],
            options={
                'verbose_name': 'Workload Standard',
                'verbose_name_plural': 'Workload Standards',
                'ordering': ['department', 'jabatan', 'nama_aktivitas'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRealization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(verbose_name='Tanggal Selesai')),
                ('lokasi', models.CharField(blank=True, max_length=200, verbose_name='Lokasi / Platform')),
                ('instruktur', models.CharField(blank=True, max_length=200, verbose_name='Instruktur / Fasilitator')),
                ('biaya_aktual', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Biaya Aktual (Rp)')),
                ('hasil', models.CharField(choices=[('lulus', 'Lulus / Kompeten'), ('tidak_lulus', 'Tidak Lulus'), ('ikut', 'Hadir (tanpa ujian)')], default='ikut', max_length=12, verbose_name='Hasil Training')),
                ('nilai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nilai / Skor (jika ada)')),
                ('nomor_sertifikat', models.CharField(blank=True, max_length=100, verbose_name='Nomor Sertifikat')),
                ('berlaku_sampai', models.DateField(blank=True, null=True, verbose_name='Sertifikat Berlaku Sampai')),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realization', to='od.trainingplan', verbose_name='Rencana Training')),
            ],
            options={
                'verbose_name': 'Realisasi Training',
                'verbose_name_plural': 'Realisasi Training',
                'ordering': ['-tanggal_selesai'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Program Training')),
                ('kategori', models.CharField(choices=[('technical', 'Technical Skill'), ('soft_skill', 'Soft Skill'), ('leadership', 'Leadership'), ('compliance', 'Compliance / Regulasi'), ('onboarding', 'Onboarding'), ('sertifikasi', 'Sertifikasi'), ('lainnya', 'Lainnya')], default='technical', max_length=15)),
                ('metode', models.CharField(choices=[('offline', 'Offline / Tatap Muka'), ('online', 'Online / E-Learning'), ('hybrid', 'Hybrid'), ('otodidak', 'Mandiri / Otodidak')], default='offline', max_length=10)),
                ('penyelenggara', models.CharField(blank=True, max_length=200, verbose_name='Penyelenggara / Vendor')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi & Tujuan')),
                ('durasi_jam', models.DecimalField(decimal_places=1, default=8, max_digits=6, verbose_name='Durasi (jam)')),
                ('biaya_est', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Estimasi Biaya (Rp)')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='core.company')),
                ('kompetensi_terkait', models.ManyToManyField(blank=True, related_name='training_programs', to='od.competency', verbose_name='Kompetensi yang Ditingkatkan')),
            ],
            options={
                'verbose_name': 'Program Training',
                'verbose_name_plural': 'Program Training',
                'ordering': ['kategori', 'nama'],
            },
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='od.trainingprogram', verbose_name='Program Training'),
        ),
        migrations.CreateModel(
            name='FTEStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fte_ideal', models.DecimalField(decimal_places=2, help_text='Jumlah headcount ideal untuk posisi ini', max_digits=6, verbose_name='FTE Ideal')),
                ('fte_minimum', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='FTE Minimum')),
                ('dasar_perhitungan', models.TextField(blank=True, help_text='Asumsi / metode yang digunakan', verbose_name='Dasar Perhitungan')),
                ('tahun', models.IntegerField(verbose_name='Tahun Referensi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fte_standards', to='core.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fte_standards', to='core.department')),
                ('jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fte_standards', to='core.position')),
            ],
            options={
                'verbose_name': 'FTE Standard',
                'verbose_name_plural': 'FTE Standards',
                'ordering': ['department', 'jabatan'],
                'unique_together': {('company', 'department', 'jabatan', 'tahun')},
            },
        ),
        migrations.CreateModel(
            name='FTEPlanningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_analisis', models.DateField(auto_now_add=True, verbose_name='Tanggal Analisis')),
                ('headcount_aktual', models.IntegerField(verbose_name='Headcount Aktual')),
                ('fte_ideal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gap', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Gap (Aktual - Ideal)')),
                ('status', models.CharField(choices=[('over', 'Over-staffed'), ('ideal', 'Ideal'), ('under', 'Under-staffed')], max_length=10)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fte_results', to='core.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fte_results', to='core.department')),
                ('fte_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='od.ftestandard')),
                ('jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fte_results', to='core.position')),
            ],
            options={
                'verbose_name': 'FTE Planning Result',
                'verbose_name_plural': 'FTE Planning Results',
                'ordering': ['-tanggal_analisis', 'department'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('deskripsi', models.TextField(blank=True)),
                ('warna', models.CharField(default='#818cf8', max_length=7, verbose_name='Warna (hex)')),
                ('urutan', models.IntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_categories', to='core.company')),
            ],
            options={
                'verbose_name': 'Competency Category',
                'verbose_name_plural': 'Competency Categories',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.AddField(
            model_name='competency',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencies', to='od.competencycategory'),
        ),
        migrations.CreateModel(
            name='PositionCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_required', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=3, verbose_name='Level yang Dibutuhkan')),
                ('bobot', models.IntegerField(default=1, help_text='Kepentingan kompetensi ini untuk jabatan', verbose_name='Bobot (1-5)')),
                ('wajib', models.BooleanField(default=True, verbose_name='Wajib / Mandatory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_competencies', to='core.company')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_requirements', to='od.competency')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_competencies', to='core.position')),
            ],
            options={
                'verbose_name': 'Standar Kompetensi Jabatan',
                'verbose_name_plural': 'Standar Kompetensi Jabatan',
                'ordering': ['-wajib', '-bobot'],
                'unique_together': {('jabatan', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_aktual', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=1, verbose_name='Level Aktual')),
                ('metode', models.CharField(choices=[('self', 'Self Assessment'), ('manager', 'Manager Assessment'), ('360', '360° Assessment'), ('test', 'Uji Kompetensi')], default='manager', max_length=10)),
                ('catatan', models.TextField(blank=True)),
                ('tanggal_penilaian', models.DateField(auto_now_add=True, verbose_name='Tanggal Penilaian')),
                ('periode', models.CharField(help_text='Contoh: 2026', max_length=7, verbose_name='Periode (YYYY)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_competencies', to='core.company')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assessments', to='od.competency')),
                ('dinilai_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency_assessor', to='employees.employee', verbose_name='Dinilai Oleh')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessments', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Penilaian Kompetensi Karyawan',
                'verbose_name_plural': 'Penilaian Kompetensi Karyawan',
                'ordering': ['-tanggal_penilaian'],
                'unique_together': {('employee', 'competency', 'periode')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='competency',
            unique_together={('company', 'kode')},
        ),
    ]
