# Generated by Django 4.2.9 on 2026-03-14 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_demo_reset_schedule_company_last_demo_reset_and_more'),
        ('employees', '0001_initial'),
        ('od', '0002_competency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(help_text='Contoh: 2026', max_length=7, verbose_name='Periode (YYYY)')),
                ('tanggal_rencana', models.DateField(blank=True, null=True, verbose_name='Tanggal Rencana Pelaksanaan')),
                ('status', models.CharField(choices=[('rencana', 'Direncanakan'), ('disetujui', 'Disetujui'), ('berjalan', 'Sedang Berjalan'), ('selesai', 'Selesai'), ('batal', 'Dibatalkan')], default='rencana', max_length=10)),
                ('prioritas', models.IntegerField(choices=[(1, 'Tinggi'), (2, 'Sedang'), (3, 'Rendah')], default=2, verbose_name='Prioritas')),
                ('alasan', models.TextField(blank=True, verbose_name='Alasan / Kebutuhan Training')),
                ('tanggal_disetujui', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='core.company')),
                ('disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plans_disetujui', to='employees.employee', verbose_name='Disetujui Oleh')),
                ('diusulkan_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plans_diusulkan', to='employees.employee', verbose_name='Diusulkan Oleh')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='employees.employee', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Rencana Training',
                'verbose_name_plural': 'Rencana Training',
                'ordering': ['periode', 'prioritas', 'employee__nama'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRealization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(verbose_name='Tanggal Selesai')),
                ('lokasi', models.CharField(blank=True, max_length=200, verbose_name='Lokasi / Platform')),
                ('instruktur', models.CharField(blank=True, max_length=200, verbose_name='Instruktur / Fasilitator')),
                ('biaya_aktual', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Biaya Aktual (Rp)')),
                ('hasil', models.CharField(choices=[('lulus', 'Lulus / Kompeten'), ('tidak_lulus', 'Tidak Lulus'), ('ikut', 'Hadir (tanpa ujian)')], default='ikut', max_length=12, verbose_name='Hasil Training')),
                ('nilai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nilai / Skor (jika ada)')),
                ('nomor_sertifikat', models.CharField(blank=True, max_length=100, verbose_name='Nomor Sertifikat')),
                ('berlaku_sampai', models.DateField(blank=True, null=True, verbose_name='Sertifikat Berlaku Sampai')),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realization', to='od.trainingplan', verbose_name='Rencana Training')),
            ],
            options={
                'verbose_name': 'Realisasi Training',
                'verbose_name_plural': 'Realisasi Training',
                'ordering': ['-tanggal_selesai'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Program Training')),
                ('kategori', models.CharField(choices=[('technical', 'Technical Skill'), ('soft_skill', 'Soft Skill'), ('leadership', 'Leadership'), ('compliance', 'Compliance / Regulasi'), ('onboarding', 'Onboarding'), ('sertifikasi', 'Sertifikasi'), ('lainnya', 'Lainnya')], default='technical', max_length=15)),
                ('metode', models.CharField(choices=[('offline', 'Offline / Tatap Muka'), ('online', 'Online / E-Learning'), ('hybrid', 'Hybrid'), ('otodidak', 'Mandiri / Otodidak')], default='offline', max_length=10)),
                ('penyelenggara', models.CharField(blank=True, max_length=200, verbose_name='Penyelenggara / Vendor')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi & Tujuan')),
                ('durasi_jam', models.DecimalField(decimal_places=1, default=8, max_digits=6, verbose_name='Durasi (jam)')),
                ('biaya_est', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Estimasi Biaya (Rp)')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='core.company')),
                ('kompetensi_terkait', models.ManyToManyField(blank=True, related_name='training_programs', to='od.competency', verbose_name='Kompetensi yang Ditingkatkan')),
            ],
            options={
                'verbose_name': 'Program Training',
                'verbose_name_plural': 'Program Training',
                'ordering': ['kategori', 'nama'],
            },
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='od.trainingprogram', verbose_name='Program Training'),
        ),
    ]
