# Generated by Django 4.2.9 on 2026-03-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(blank=True, max_length=200)),
                ('maintenance_date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('Rutin', 'Rutin'), ('Perbaikan', 'Perbaikan'), ('Kalibrasi', 'Kalibrasi'), ('Inspeksi', 'Inspeksi'), ('Darurat', 'Darurat')], default='Rutin', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('technician', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenance',
                'ordering': ['-maintenance_date'],
            },
        ),
    ]
