# Generated by Django 4.2.9 on 2026-03-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('industrial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeraturanPerusahaanSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Dokumen')),
                ('versi', models.CharField(blank=True, max_length=50, verbose_name='Versi / Revisi')),
                ('dokumen', models.FileField(upload_to='pp_sp/', verbose_name='File Dokumen')),
                ('jenis', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('other', 'Lainnya')], default='pdf', max_length=10)),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('is_aktif', models.BooleanField(default=True, verbose_name='Aktif (berlaku)')),
                ('diunggah_oleh', models.CharField(blank=True, max_length=100, verbose_name='Diunggah oleh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp_sp_docs', to='core.company', verbose_name='Perusahaan')),
            ],
            options={
                'verbose_name': 'Peraturan Perusahaan SP',
                'verbose_name_plural': 'Peraturan Perusahaan SP',
                'ordering': ['-created_at'],
            },
        ),
    ]
