# Generated by Django 4.2.9 on 2026-03-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('asset_name', models.CharField(max_length=200)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('useful_life', models.IntegerField(default=5)),
                ('residual_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired'), ('BROKEN', 'Broken'), ('RESERVED', 'Reserved')], default='ACTIVE', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(choices=[('Baik', 'Baik'), ('Rusak Ringan', 'Rusak Ringan'), ('Rusak Berat', 'Rusak Berat'), ('Dalam Perbaikan', 'Dalam Perbaikan')], default='Baik', max_length=20)),
                ('warranty_date', models.DateField(blank=True, null=True)),
                ('cabinet', models.CharField(blank=True, max_length=100, verbose_name='Lemari/Rak')),
                ('invoice', models.CharField(blank=True, max_length=100, verbose_name='Nomor Nota')),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('asset_type', models.CharField(choices=[('Tangible', 'Berwujud'), ('Intangible', 'Tidak Berwujud'), ('Custom', 'Custom')], default='Tangible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('Garis Lurus', 'Garis Lurus (Straight Line)'), ('Saldo Menurun', 'Saldo Menurun (Declining Balance)'), ('Saldo Menurun Ganda', 'Saldo Menurun Ganda (Double Declining)'), ('Jumlah Angka Tahun', 'Jumlah Angka Tahun (Sum of Years)'), ('Unit Produksi', 'Unit Produksi (Units of Production)')], default='Garis Lurus', max_length=50)),
                ('useful_life', models.IntegerField(default=5)),
                ('residual_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('rate', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nilai Penyusutan',
                'verbose_name_plural': 'Nilai Penyusutan',
            },
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('monthly_depreciation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
            options={
                'verbose_name': 'Depresiasi',
                'verbose_name_plural': 'Depresiasi',
                'ordering': ['asset', 'year', 'month'],
            },
        ),
    ]
