# Generated by Django 4.2.9 on 2026-03-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Jam Masuk')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Jam Keluar')),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Tidak Hadir', 'Tidak Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Cuti', 'Cuti'), ('Libur', 'Libur'), ('WFH', 'WFH')], default='Hadir', max_length=20)),
                ('keterlambatan', models.IntegerField(default=0, help_text='Menit keterlambatan')),
                ('lembur_jam', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Jam Lembur')),
                ('lembur_upah', models.BigIntegerField(default=0, verbose_name='Upah Lembur')),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Absensi',
                'verbose_name_plural': 'Absensi',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Hari Libur')),
                ('tanggal', models.DateField()),
                ('keterangan', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Hari Libur',
                'verbose_name_plural': 'Hari Libur',
                'ordering': ['tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_cuti', models.CharField(choices=[('Cuti Tahunan', 'Cuti Tahunan'), ('Cuti Sakit', 'Cuti Sakit'), ('Cuti Melahirkan', 'Cuti Melahirkan'), ('Cuti Besar', 'Cuti Besar'), ('Cuti Penting', 'Cuti Penting'), ('Ijin', 'Ijin')], max_length=30, verbose_name='Tipe Cuti')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(verbose_name='Tanggal Selesai')),
                ('jumlah_hari', models.IntegerField(default=1, verbose_name='Jumlah Hari')),
                ('alasan', models.TextField(verbose_name='Alasan')),
                ('dokumen', models.FileField(blank=True, null=True, upload_to='leave_docs/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Disetujui'), ('Rejected', 'Ditolak'), ('Cancelled', 'Dibatalkan')], default='Pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('catatan_approval', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuti / Ijin',
                'verbose_name_plural': 'Cuti / Ijin',
                'ordering': ['-created_at'],
            },
        ),
    ]
