# Generated by Django 4.2.9 on 2026-03-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='tipe',
            field=models.CharField(choices=[('Nasional', 'Nasional (SKB/Keppres)'), ('Bersama', 'Cuti Bersama'), ('Internal', 'Kebijakan Perusahaan')], default='Nasional', max_length=20, verbose_name='Tipe Libur'),
        ),
    ]
