# Generated by Django 4.2.9 on 2026-03-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Pool Investasi Ikira', max_length=100)),
                ('total_dana', models.DecimalField(decimal_places=0, default=4000000, max_digits=12, verbose_name='Total Dana Pool (Rp)')),
                ('modal_founder', models.DecimalField(decimal_places=0, default=2000000, max_digits=12, verbose_name='Modal Founder (Rp)')),
                ('persen_investor', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='% Nett untuk Investor Pool (%)')),
                ('target_return_x', models.DecimalField(decimal_places=1, default=2, max_digits=4, verbose_name='Target Return (x lipat)')),
                ('aktif', models.BooleanField(default=True)),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Internal Founder')),
            ],
            options={
                'verbose_name': 'Konfigurasi Pool Investasi',
                'verbose_name_plural': 'Konfigurasi Pool Investasi',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('done', 'Selesai'), ('ongoing', 'Sedang Berjalan'), ('planned', 'Direncanakan')], default='planned', max_length=10)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('urutan', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='RevenueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.DateField()),
                ('mrr', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('biaya_ops', models.DecimalField(decimal_places=0, default=800000, max_digits=12, verbose_name='Biaya Operasional (Rp)')),
                ('client_baru', models.IntegerField(default=0)),
                ('catatan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Revenue Entry',
                'verbose_name_plural': 'Revenue Entries',
                'ordering': ['-bulan'],
                'unique_together': {('bulan',)},
            },
        ),
        migrations.CreateModel(
            name='InvestorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('aktif', models.BooleanField(default=True)),
                ('modal_investasi', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Modal Investasi (Rp)')),
                ('total_diterima', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total Sudah Diterima (Rp)')),
                ('tanggal_mulai', models.DateField(blank=True, null=True)),
                ('catatan_founder', models.TextField(blank=True, verbose_name='Catatan Founder (rahasia)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='investor.investorpool')),
            ],
            options={
                'verbose_name': 'Akun Investor',
                'verbose_name_plural': 'Akun Investor',
            },
        ),
        migrations.CreateModel(
            name='PayoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.DateField()),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=12)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='investor.investoraccount')),
            ],
            options={
                'verbose_name': 'Riwayat Payout',
                'verbose_name_plural': 'Riwayat Payout',
                'ordering': ['-bulan'],
                'unique_together': {('investor', 'bulan')},
            },
        ),
    ]
