# Generated by Django 4.2.9 on 2026-03-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Investor')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Akun Investor',
                'verbose_name_plural': 'Akun Investor',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('done', 'Selesai'), ('ongoing', 'Sedang Berjalan'), ('planned', 'Direncanakan')], default='planned', max_length=10)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('urutan', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='RevenueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.DateField(help_text='Isi tanggal 1 dari bulan yang dimaksud')),
                ('mrr', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='MRR (Rp)')),
                ('client_baru', models.IntegerField(default=0)),
                ('catatan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Revenue Entry',
                'verbose_name_plural': 'Revenue Entries',
                'ordering': ['-bulan'],
                'unique_together': {('bulan',)},
            },
        ),
    ]
