# Generated by Django 4.2.9 on 2026-03-15 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Pool Investasi Ikira', max_length=100)),
                ('total_dana', models.DecimalField(decimal_places=0, default=4000000, max_digits=12, verbose_name='Total Dana Pool (Rp)')),
                ('modal_founder', models.DecimalField(decimal_places=0, default=2000000, max_digits=12, verbose_name='Modal Founder (Rp)')),
                ('persen_investor', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='% Nett untuk Investor Pool (%)')),
                ('target_return_x', models.DecimalField(decimal_places=1, default=2, max_digits=4, verbose_name='Target Return (x lipat)')),
                ('aktif', models.BooleanField(default=True)),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Internal Founder')),
            ],
            options={
                'verbose_name': 'Konfigurasi Pool Investasi',
                'verbose_name_plural': 'Konfigurasi Pool Investasi',
            },
        ),
        migrations.AddField(
            model_name='investoraccount',
            name='catatan_founder',
            field=models.TextField(blank=True, verbose_name='Catatan Founder (rahasia)'),
        ),
        migrations.AddField(
            model_name='investoraccount',
            name='modal_investasi',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Modal Investasi (Rp)'),
        ),
        migrations.AddField(
            model_name='investoraccount',
            name='tanggal_mulai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investoraccount',
            name='total_diterima',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total Sudah Diterima (Rp)'),
        ),
        migrations.AddField(
            model_name='revenueentry',
            name='biaya_ops',
            field=models.DecimalField(decimal_places=0, default=800000, max_digits=12, verbose_name='Biaya Operasional (Rp)'),
        ),
        migrations.AlterField(
            model_name='investoraccount',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='revenueentry',
            name='bulan',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='revenueentry',
            name='mrr',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='investoraccount',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='investor.investorpool'),
        ),
        migrations.CreateModel(
            name='PayoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.DateField()),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=12)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='investor.investoraccount')),
            ],
            options={
                'verbose_name': 'Riwayat Payout',
                'verbose_name_plural': 'Riwayat Payout',
                'ordering': ['-bulan'],
                'unique_together': {('investor', 'bulan')},
            },
        ),
    ]
