# Generated by Django 4.2.9 on 2026-03-13 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_position_parent_and_more'),
        ('payroll', '0003_siteallowancerule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteallowancerule',
            name='jabatan',
            field=models.ForeignKey(blank=True, help_text='Kosongkan = berlaku untuk semua jabatan di site ini', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.position', verbose_name='Jabatan (opsional)'),
        ),
    ]
